################################################################################
# Module outputs. CONTRACT FILE — these field names are part of the public
# interface consumed by:
#   - modules/azure/ansible/inventory.py (the shared dynamic-inventory script)
#   - The `./range creds`, `./range list`, `./range inventory` CLI commands
#   - operator-facing JSON outputs surfaced into labs/<range>/*.json
#
# This file is INTENTIONALLY a field-by-field mirror of
# modules/azure/outputs.tf. Any drift between the two will break the
# inventory generator, which JSON-walks `terraform output -json hosts`
# (or `ansible_inventory`) and assumes the same shape regardless of
# provider. When you add a new output here, add the same-named output to
# the Azure file with the same fields — and vice versa.
################################################################################

# ── Guacamole entry-point info ───────────────────────────────────────────────

output "guacamole_url" {
  description = "Public URL of the Guacamole web UI. When services.guacamole.dns_zone_name + custom_hostname are set, this resolves to https://<custom_hostname>.<dns_zone_name>/ (certbot DNS-01 wildcard); otherwise it falls back to https://<public-ip>/ with a self-signed cert."
  value = (
    var.services.guacamole.enabled
    ? "https://${try(local.guac_effective_fqdn, google_compute_address.guacamole[0].address)}"
    : "guacamole disabled"
  )
}

# Bare FQDN (no scheme) — consumed by inventory.py so the Ansible
# guacamole role can run certbot against this hostname when the cert
# on the live VM is still the self-signed fallback. Falls back to the
# public IP literal if no custom hostname is configured (the role then
# skips LE issuance because it would fail to validate an IP).
output "guacamole_fqdn" {
  value = (
    var.services.guacamole.enabled
    ? try(local.guac_effective_fqdn, google_compute_address.guacamole[0].address)
    : ""
  )
}

output "guacamole_acme_email" {
  value = var.services.guacamole.acme_email
}

output "guacamole_admin_user" {
  value = var.services.guacamole.admin_user
}

output "guacamole_admin_password" {
  description = "Operator's Guacamole admin password. When the scenario YAML left it blank (or set to a known-weak default like 'Lab!Guac1'), this is a per-deploy random 28-char password generated by random_password.guacamole_admin."
  value       = local.effective_guacamole_admin_password
  sensitive   = true
}

# ── Operator SSH artifacts ───────────────────────────────────────────────────

output "operator_ssh_private_key_path" {
  description = "Path to the auto-generated operator SSH private key. Use with `ssh -i <path> ranger@<vm-ip>`. Auto-generated unless the scenario YAML provides a real services.adaptix.ssh_pubkey."
  value       = local_sensitive_file.operator_private_key.filename
}

output "lab_dir" {
  description = "Per-deploy directory containing the SSH keypair and credentials.txt for this range. `./range destroy` removes this directory."
  value       = local.lab_dir
}

output "operator_ssh_public_key" {
  description = "Operator SSH public key embedded in every Linux VM's authorized_keys. Same key whether auto-generated or scenario-provided."
  value       = local.effective_ssh_pubkey
}

# ── ELK ──────────────────────────────────────────────────────────────────────

output "elk_kibana_url" {
  description = "Kibana URL — public when services.elk.public_ip = true (default), otherwise the internal address operators reach via Guacamole/Kali."
  value = (
    !var.services.elk.enabled ? "elk disabled" :
    var.services.elk.public_ip
    ? "http://${google_compute_address.elk[0].address}:5601"
    : "http://${local.elk_hub_ip}:5601  (no public IP — open via Guacamole/Kali browser)"
  )
}

# ── Student / operator credentials ───────────────────────────────────────────

output "student_logins" {
  description = "Per-student Guacamole credentials."
  value = [
    for u in var.student_users : {
      student_id = u.student_id
      username   = u.username
      password   = u.password
    }
  ]
  sensitive = true
}

# ── Quick machine IP map for debugging ───────────────────────────────────────

output "machine_ips" {
  description = "Machine name -> private IP, useful for debugging."
  value = {
    for m in var.machines :
    m.name => local.machine_private_ip[m.name]
  }
}

# ── High-level summary banner ────────────────────────────────────────────────

output "summary" {
  value = {
    range          = var.range_name
    students       = var.students.count
    machines_total = length(var.machines)
    shared_total   = length(var.shared_machines)
    lockdown       = var.lockdown
    advanced_c2    = var.advanced_c2.enabled
  }
}

# ── Shared infra (Ghostwriter / SteppingStones / RedELK) ─────────────────────

output "shared_infra" {
  description = "Per-tool address + SSH login for the shared red-team infra."
  value = {
    for s in var.shared_machines :
    s.name => {
      role       = s.role
      public_ip  = s.public_ip ? google_compute_address.shared[s.name].address : null
      private_ip = google_compute_instance.shared[s.name].network_interface[0].network_ip
      ssh_user   = s.linux_user
      web_url = s.public_ip ? (
        s.role == "ghostwriter" ? "https://${google_compute_address.shared[s.name].address}/" :
        s.role == "stepping-stones" ? "http://${google_compute_address.shared[s.name].address}:8000/" :
        s.role == "redelk" ? "http://${google_compute_address.shared[s.name].address}:5601/" :
        "http://${google_compute_address.shared[s.name].address}/"
        ) : (
        # No public IP — operator reaches the web UI through Guacamole
        # (browser running on the Kali workstation, navigating to the
        # private IP).
        s.role == "ghostwriter" ? "https://${google_compute_instance.shared[s.name].network_interface[0].network_ip}/  (via Guacamole/Kali)" :
        s.role == "stepping-stones" ? "http://${google_compute_instance.shared[s.name].network_interface[0].network_ip}:8000/  (via Guacamole/Kali)" :
        s.role == "redelk" ? "http://${google_compute_instance.shared[s.name].network_interface[0].network_ip}:5601/  (via Guacamole/Kali)" :
        "http://${google_compute_instance.shared[s.name].network_interface[0].network_ip}/  (via Guacamole/Kali)"
      )
    }
  }
}

output "shared_infra_credentials" {
  description = "SSH + web-admin credentials for shared infra boxes."
  sensitive   = true
  value = {
    for s in var.shared_machines :
    s.name => {
      ssh_user     = s.linux_user
      ssh_password = s.linux_password
      # Web-admin login for boxes exposing a UI. stepping-stones creates
      # its Django superuser as linux_user/linux_password in userdata,
      # so those ARE the web-admin creds (deterministic, terraform-owned).
      # ghostwriter/redelk web passwords are ansible-managed (see their
      # role reports), so terraform surfaces null + a note here.
      web_admin_user = (
        s.role == "stepping-stones" ? s.linux_user :
        s.role == "ghostwriter" ? "admin" :
        s.role == "redelk" ? "elastic" :
        null
      )
      web_admin_password = (
        s.role == "stepping-stones" ? s.linux_password :
        null
      )
      web_admin_note = (
        s.role == "ghostwriter" ? "password set by ansible (ghostwriter_admin_password); see ghostwriter role report" :
        s.role == "redelk" ? "password set by ansible (redelk_es_password); see redelk role report" :
        null
      )
    }
  }
}

# ── Per-C2 teamserver connection bundles ─────────────────────────────────────
# These are operator-facing fields used by `./range creds`. Each block
# filters var.machines for its specific role.

output "adaptix_connections" {
  description = "Per-student AdaptixC2 teamserver coordinates for the operator client."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id     = m.student_id
      private_ip     = local.machine_private_ip[m.name]
      commander_port = 9000
      operator_user  = m.linux_user
      password       = local.effective_adaptix_password[m.student_id]
    } if m.role == "c2-server"
  }
}

output "mythic_connections" {
  description = "Per-student Mythic teamserver coordinates (web UI + admin creds)."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id     = m.student_id
      private_ip     = local.machine_private_ip[m.name]
      web_ui_port    = 7443 # Mythic upstream default
      admin_user     = "mythic_admin"
      admin_password = local.effective_mythic_password[m.student_id]
    } if m.role == "c2-mythic"
  }
}

output "brc4_connections" {
  description = "Per-student Brute Ratel C4 teamserver coordinates. The `automation_password` is a SECOND operator account on the BRC4 profile (user_list.automation) used by the brc4_payload Ansible role so its API session doesn't collide with the operator's Commander GUI session on the shared :9000 port."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id          = m.student_id
      private_ip          = local.machine_private_ip[m.name]
      commander_port      = 9000
      admin_user          = "admin"
      admin_password      = local.effective_brc4_password[m.student_id]
      automation_user     = "automation"
      automation_password = local.effective_brc4_automation_password[m.student_id]
    } if m.role == "c2-brc4"
  }
}

output "sliver_connections" {
  description = "Per-student Sliver C2 teamserver coordinates. Operator config file lives at /opt/sliver-cfg/operator.cfg on the teamserver — SCP it down via Guacamole's Kali RDP session and `sliver-client import operator.cfg`."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id       = m.student_id
      private_ip       = local.machine_private_ip[m.name]
      multiplayer_port = 31337
      operator_name    = "operator"
      operator_cfg     = "/opt/sliver-cfg/operator.cfg"
      seed_password    = local.effective_sliver_password[m.student_id]
    } if m.role == "c2-sliver"
  }
}

# ── Per-CDN header tables (for operator origin-header configuration) ─────────

output "cdn_headers" {
  description = "Per-student-per-stack-per-CDN X-Api-* (name, value, port) tuples for origin header config."
  sensitive   = true
  value = {
    for sid in local.students :
    sid => {
      adaptix = local.cdn_headers["adaptix"][sid]
      mythic  = local.cdn_headers["mythic"][sid]
      brc4    = local.cdn_headers["brc4"][sid]
      sliver  = local.cdn_headers["sliver"][sid]
    }
  }
}

# ── Cloud CDN front (parallel cdn.tf agent owns the resource) ────────────────
# Same shape as the Azure advanced_c2 output, but resolves to GCP Cloud CDN /
# Global External HTTP(S) LB resources owned by the parallel cdn.tf agent.
# try() lets this file evaluate even before that agent's resources exist;
# the output is `null` in that case (matches Azure's `enabled=false` shape).
output "advanced_c2" {
  description = "GCP Cloud CDN / global LB endpoint and per-redirector domains. null when disabled."
  value = try(local.afd_enabled, false) ? {
    profile_id   = try(google_compute_global_forwarding_rule.main[0].id, null)
    profile_name = try(google_compute_global_forwarding_rule.main[0].name, null)
    endpoint     = try(google_compute_global_address.main[0].address, null)
    routes = {
      for name, m in try(local.redirectors, {}) :
      name => {
        student_id = m.student_id
        fronts     = m.fronts
        subdomain  = try(local.redirector_subdomain[name], null)
        fqdn       = "${try(local.redirector_subdomain[name], "")}.${var.advanced_c2.domain}"
        public_ip  = try(google_compute_address.redirector[name].address, null)
      }
    }
  } : null
}

################################################################################
# Ansible inventory feed — the single source of truth consumed by
# modules/azure/ansible/inventory.py.
#
# Designing the data shape HERE (not in inventory.py) keeps the layer
# above pure JSON-walking and lets terraform compute everything ansible
# needs (per-VM role, IP, jump-host, per-student creds, CDN headers).
#
# A note on jump hosts (mirrors the Azure note):
#   Linux teamserver VMs (c2-server, c2-mythic, c2-brc4, c2-sliver) have NO
#   public IP. Their paired redirector (<vm-name>-redir) DOES have a public
#   IP. Ansible reaches the teamserver by SSHing to the redirector and
#   ProxyJumping to the teamserver's private IP. The inventory emits
#   `ansible_ssh_common_args` with the ProxyJump string already filled in.
################################################################################

output "ansible_inventory" {
  description = "Structured inventory data for modules/azure/ansible/inventory.py — one entry per Linux VM with the SSH params (host, user, ProxyJump if needed) and per-student vars."
  sensitive   = true
  value = {
    ssh_private_key_path = local_sensitive_file.operator_private_key.filename

    # Map of "<range>-<vm>-redir" -> redirector public IP. inventory.py
    # builds the jump-host lookup as `redirector_public_ips[f"{host.name}-redir"]`,
    # and host.name is the range-prefixed form (vms.tf emits
    # google_compute_instance.machine[m.name].name as "${var.range_name}-${m.name}").
    # MUST be the range-prefixed key or ProxyJump silently breaks — see
    # the comment in modules/azure/outputs.tf around line 250.
    redirector_public_ips = {
      for name, m in try(local.redirectors, {}) :
      "${var.range_name}-${name}" => try(google_compute_address.redirector[name].address, null)
    }

    operator_ian = local.operator_ian

    guacamole_login_title = (
      var.services.guacamole.enabled
      ? var.services.guacamole.login_title
      : "Guidem CWR"
    )

    guacamole_fqdn = (
      var.services.guacamole.enabled
      ? try(local.guac_effective_fqdn, google_compute_address.guacamole[0].address)
      : ""
    )
    guacamole_acme_email = var.services.guacamole.acme_email

    # Base64 of the rendered manifest (same content cloud-init bakes into
    # /opt/guac/manifest.json at first boot). The Guac VM has
    # lifecycle.ignore_changes = [metadata["user-data"]], so once that
    # initial bake happens the manifest never updates from terraform. The
    # guacamole ansible role writes THIS value to /opt/guac/manifest.json
    # before running register.py so subsequent edits to services.tf
    # actually land on the live Guacamole DB after a `./range repair`.
    guacamole_manifest_b64 = base64encode(local.guac_manifest)

    # Per-VM ansible host entry. inventory.py expects EXACTLY these
    # field names — adding/removing fields requires a parallel
    # inventory.py change.
    hosts = concat(
      # ---- Per-student VMs (c2 + redirector + targets + windows roles) ----
      # IMPORTANT: `name` MUST equal "${var.range_name}-${m.name}" because
      # the resource is created with that name in vms.tf, and inventory.py
      # keys jump-host lookups off the resource name. Short-name keying
      # silently breaks ProxyJump.
      [
        for m in var.machines : {
          name       = "${var.range_name}-${m.name}"
          role       = m.role
          student_id = m.student_id
          private_ip = local.machine_private_ip[m.name]
          # Public IP only on c2-redirector machines — every other role has
          # no external IP. try() handles the absence cleanly.
          public_ip      = try(google_compute_address.redirector[m.name].address, null)
          ssh_user       = m.linux_user
          linux_password = m.linux_password
          # The ACTUAL admin USERNAME on the Windows VM (vms.tf sets this
          # via the windows-startup-script-ps1 metadata key — `net user
          # ${m.win_admin_user} ...`). MUST be what ansible authenticates
          # as. Without this, inventory.py falls back to ssh_user="ranger"
          # and WinRM rejects with "credentials rejected".
          windows_admin_user = m.win_admin_user
          # The ACTUAL admin password — populated by
          # random_password.domain_admin[student_id] at apply time and
          # planted as the local admin password in vms.tf's windows-*
          # branch. inventory.py uses this for ansible_password on Windows
          # hosts (winrm basic auth). Null on non-Windows VMs.
          windows_admin_password = try(local.effective_domain_password[m.student_id], null)
          # Per-role auth bundle. Ansible roles pick the fields they need;
          # missing fields are simply null on irrelevant VMs.
          adaptix_password = try(local.effective_adaptix_password[m.student_id], null)
          mythic_password  = try(local.effective_mythic_password[m.student_id], null)
          brc4_password    = try(local.effective_brc4_password[m.student_id], null)
          # BRC4 second operator ("automation") — see brc4_connections doc.
          brc4_automation_password = try(local.effective_brc4_automation_password[m.student_id], null)
          sliver_password          = try(local.effective_sliver_password[m.student_id], null)
          cdn_headers = try(local.cdn_headers[
            m.role == "c2-server" ? "adaptix" :
            m.role == "c2-mythic" ? "mythic" :
            m.role == "c2-brc4" ? "brc4" :
            m.role == "c2-sliver" ? "sliver" : "adaptix"
          ][m.student_id], null)
          # Per-CDN beacon callback addresses for this teamserver. On GCP
          # the parallel cdn.tf agent owns `local.gcp_callback_for` (same
          # shape as Azure's azure_callback_for); try() defaults the
          # "azure" CDN slot to a CHANGEME placeholder when that local
          # isn't defined yet.
          #
          # AdaptixServer's BeaconHTTP listener parses each
          # callback_addresses entry with `net.SplitHostPort` — feeding
          # a full URL yields "Invalid address". So we emit just
          # `host:port`; the listener applies ssl:true and uri:/endpoint
          # separately.
          adaptix_callbacks = (m.role == "c2-server"
            ? {
              for cdn in local.cdn_names :
              cdn => (
                cdn == "azure"
                ? "${try(local.gcp_callback_for["c2-server"][m.student_id], "CHANGEME-azure-${m.student_id}")}:443"
                : "CHANGEME-${cdn}-${m.student_id}:443"
              )
            }
            : null
          )
          # Mythic-side equivalent. Mythic's http C2 profile params take
          # a FULL URL for `callback_host` (unlike Adaptix's bare
          # host:port). When AFD/CDN is on, the redirector's fronted
          # subdomain becomes the beacon callback.
          mythic_callback_host = (m.role == "c2-mythic"
            ? "https://${try(local.gcp_callback_for["c2-mythic"][m.student_id], "CHANGEME-mythic-${m.student_id}")}"
            : null
          )
          # BRC4-side equivalent. listeners.tf renders a per-student
          # c2.profile (5 HTTPS listeners on :8443-:8447 + commander).
          # c2-brc4.sh userdata drops it at boot; the brc4 Ansible role
          # reads it back as `terra_brc4_profile`. Null on non-c2-brc4.
          brc4_profile = (m.role == "c2-brc4"
            ? try(local.brc4_profile[m.student_id], null)
            : null
          )
          # Same role filter as the Azure side. inventory.py's
          # role_to_groups + WINDOWS_ROLES sets MUST list every role
          # appearing here, or ansible will see a host it can't connect to.
          } if contains([
            "c2-server", "c2-mythic", "c2-brc4", "c2-sliver", "c2-redirector",
            "attacker", "linux-target",
            "windows-dc", "windows-member", "windows-workstation",
            "windows-analyst", "windows-blank", "windows-persona",
        ], m.role)
      ],
      # ---- Guacamole (1 VM, identified by name suffix) ----
      var.services.guacamole.enabled ? [{
        name                     = "${var.range_name}-guac"
        role                     = "guacamole"
        student_id               = "shared"
        private_ip               = google_compute_instance.guacamole[0].network_interface[0].network_ip
        public_ip                = google_compute_address.guacamole[0].address
        ssh_user                 = "guacadmin"
        linux_password           = local.effective_guacamole_admin_password
        windows_admin_user       = null
        windows_admin_password   = null
        adaptix_password         = null
        mythic_password          = null
        brc4_password            = null
        brc4_automation_password = null
        sliver_password          = null
        cdn_headers              = null
        adaptix_callbacks        = null
        mythic_callback_host     = null
        brc4_profile             = null
      }] : [],
      # ---- Shared infra (RedELK / Ghostwriter / SteppingStones) ----
      # Range-prefixed name to match the actual GCE instance name (see
      # shared_infra.tf — google_compute_instance.shared.name is
      # "${var.range_name}-${each.key}").
      [
        for s in var.shared_machines : {
          name                     = "${var.range_name}-${s.name}"
          role                     = s.role
          student_id               = "shared"
          private_ip               = google_compute_instance.shared[s.name].network_interface[0].network_ip
          public_ip                = s.public_ip ? google_compute_address.shared[s.name].address : null
          ssh_user                 = s.linux_user
          linux_password           = s.linux_password
          windows_admin_user       = null
          windows_admin_password   = null
          adaptix_password         = null
          mythic_password          = null
          brc4_password            = null
          brc4_automation_password = null
          sliver_password          = null
          cdn_headers              = null
          adaptix_callbacks        = null
          mythic_callback_host     = null
          brc4_profile             = null
        }
      ],
    )
  }
}

# ── Operator credentials sheet (per-student randoms) ─────────────────────────

output "student_credentials" {
  description = "Per-student random Domain Admin / Adaptix / Mythic / BRC4 / Sliver passwords. Operator-only."
  sensitive   = true
  value = {
    for sid in local.students :
    sid => {
      domain_admin_user        = var.domain.admin_user
      domain_admin_password    = local.effective_domain_password[sid]
      adaptix_teamserver_pw    = local.effective_adaptix_password[sid]
      mythic_admin_user        = "mythic_admin"
      mythic_admin_password    = local.effective_mythic_password[sid]
      brc4_teamserver_password = local.effective_brc4_password[sid]
      brc4_automation_password = local.effective_brc4_automation_password[sid]
      sliver_seed_password     = local.effective_sliver_password[sid]
    }
  }
}
