################################################################################
# Per-deploy lab artifacts (credentials, connection info) written under
# <repo>/labs/<range_name>/ alongside the SSH keypair from operator_ssh.tf.
#
# Files produced:
#   labs/<range_name>/
#     operator-id_ed25519          private key       (0600, sensitive)
#     operator-id_ed25519.pub      public key        (0644)
#     credentials.txt              human-readable    (0600, sensitive)
#     student-credentials.json     structured        (0600, sensitive)
#     guacamole.txt                quick-access URL  (0644)
#     cdn-headers.json             per-CDN headers   (0600, sensitive)
#
# `./range destroy` removes this directory after terraform destroy finishes.
################################################################################

# All file resources share local.lab_dir defined in operator_ssh.tf.

# --- guacamole.txt --- public-info bits the operator wants in one place.
resource "local_file" "lab_guacamole_info" {
  count           = var.services.guacamole.enabled ? 1 : 0
  filename        = "${local.lab_dir}/guacamole.txt"
  file_permission = "0644"
  content = <<-EOT
    Guacamole access for range "${var.range_name}"
    =============================================

    URL:        https://${azurerm_public_ip.guacamole[0].fqdn}
    Admin user: ${var.services.guacamole.admin_user}

    Per-student logins:
    %{ for u in var.student_users ~}
      ${u.username}    (student ${u.student_id})
    %{ endfor ~}
    (passwords are in credentials.txt, kept 0600.)
  EOT
}

# --- credentials.txt --- the kitchen-sink reference card.
# Contains operator + all per-student passwords. Mode 0600 because
# of the sensitive content.
resource "local_sensitive_file" "lab_credentials" {
  filename        = "${local.lab_dir}/credentials.txt"
  file_permission = "0600"
  content = <<-EOT
    ============================================================
    terra-range "${var.range_name}" — operator credentials sheet
    ============================================================
    Generated by terraform on apply. Regenerated whenever
    random_password.* values rotate. Keep this file private.

    %{ if var.services.guacamole.enabled ~}
    ----- Guacamole ---------------------------------------------
    URL:                https://${azurerm_public_ip.guacamole[0].fqdn}
    Admin user:         ${var.services.guacamole.admin_user}
    Admin password:     ${local.effective_guacamole_admin_password}

    Per-student logins (web UI):
    %{ for u in var.student_users ~}
      ${u.username}  /  ${u.password}     (student_id=${u.student_id})
    %{ endfor ~}
    %{ endif ~}

    ----- SSH key (operator) ------------------------------------
    Private key path:   ${local.lab_dir}/operator-id_ed25519
    Public  key path:   ${local.lab_dir}/operator-id_ed25519.pub
    Linux user (all):   (per-machine; see machine_ips below)

    ----- C2 teamserver credentials (per-student) ---------------
    Domain admin user:  ${var.domain.admin_user}
    %{ for sid in local.students ~}
    student "${sid}":
      domain_admin_password    : ${local.effective_domain_password[sid]}
      adaptix_teamserver_pw    : ${local.effective_adaptix_password[sid]}
      mythic_admin_user        : mythic_admin
      mythic_admin_password    : ${local.effective_mythic_password[sid]}
        NOTE: terraform's mythic_admin_password may DIVERGE from the
        value actually in use on the box (mythic-cli races cloud-init
        and sometimes generates its own random password). The truth
        lives in /opt/mythic/.env on the Mythic VM — run
        `./range repair --limit mythic` to see the live value
        surfaced in the role's report.
      brc4_teamserver_password : ${local.effective_brc4_password[sid]}
      sliver_seed_password     : ${local.effective_sliver_password[sid]}
    %{ endfor ~}

    ----- Extra operator "ian" (created on apply by Ansible roles) ---
    On Adaptix (10.<n>.1.5:9000):
      username : ${local.operator_ian.username}
      password : ${local.operator_ian.adaptix_password}
    On Mythic (https://10.<n>.1.7:7443):
      username : ${local.operator_ian.username}
      password : ${local.operator_ian.mythic_password}
    On Sliver (10.<n>.1.11:31337):
      sliver uses cert-based gRPC auth — no password.
      Operator config at /opt/sliver-cfg/ian.cfg on the Sliver VM.
      SCP it down with:
        scp -i ${local.lab_dir}/operator-id_ed25519 \
          ranger@10.<n>.1.11:/opt/sliver-cfg/ian.cfg ~/Desktop/Tools/
      Then on Kali: ./sliver-client import ian.cfg
                    ./sliver-client

    ----- Machine private IPs -----------------------------------
    %{ for m in var.machines ~}
      ${m.name}    ${azurerm_network_interface.machine[m.name].private_ip_address}    role=${m.role}    user=${m.linux_user}
    %{ endfor ~}

    ----- Reachability ------------------------------------------
    Most VMs have no public IP. To SSH to a teamserver:
      # ProxyJump through guac (the ansible controller):
      ssh -i ${local.lab_dir}/operator-id_ed25519 \
        -o ProxyCommand='ssh -i ${local.lab_dir}/operator-id_ed25519 -W %h:%p guacadmin@${var.services.guacamole.enabled ? azurerm_public_ip.guacamole[0].ip_address : "<no-guac>"}' \
        ranger@<private-ip>

    Or run any ad-hoc Ansible command via:
      ./range ansible <group> -m <module> -a "<args>"
    ============================================================
  EOT
}

# --- student-credentials.json --- structured, for scripts.
# Same shape as the `student_credentials` terraform output, but
# materialized to disk for convenience (no `terraform output` round-trip).
resource "local_sensitive_file" "lab_student_credentials_json" {
  filename        = "${local.lab_dir}/student-credentials.json"
  file_permission = "0600"
  content = jsonencode({
    for sid in local.students :
    sid => {
      domain_admin_user        = var.domain.admin_user
      domain_admin_password    = local.effective_domain_password[sid]
      adaptix_teamserver_pw    = local.effective_adaptix_password[sid]
      mythic_admin_user        = "mythic_admin"
      mythic_admin_password    = local.effective_mythic_password[sid]
      brc4_teamserver_password = local.effective_brc4_password[sid]
      sliver_seed_password     = local.effective_sliver_password[sid]
    }
  })
}

# --- cdn-headers.json --- per-student / per-CDN X-Api header tuples.
# Operators paste these into CloudFront / Fastly / workers.dev origin
# header config when wiring up additional CDNs.
resource "local_sensitive_file" "lab_cdn_headers_json" {
  filename        = "${local.lab_dir}/cdn-headers.json"
  file_permission = "0600"
  content = jsonencode({
    for sid in local.students :
    sid => {
      adaptix = local.cdn_headers["adaptix"][sid]
      mythic  = local.cdn_headers["mythic"][sid]
      brc4    = local.cdn_headers["brc4"][sid]
      sliver  = local.cdn_headers["sliver"][sid]
    }
  })
}
