output "guacamole_url" {
  description = "Public URL of the Guacamole web UI. Defaults to the Azure-assigned cloudapp.azure.com FQDN; when services.guacamole.custom_hostname + dns_zone_name are set, swaps to <custom_hostname>.<dns_zone_name> instead. certbot acquires a browser-trusted Let's Encrypt cert for whichever FQDN is effective."
  value = (
    var.services.guacamole.enabled
    ? "https://${local.guac_effective_fqdn}"
    : "guacamole disabled"
  )
}

# Bare FQDN (no scheme) — consumed by inventory.py so the Ansible
# guacamole role can run certbot against this hostname when the cert
# on the live VM is still the self-signed fallback. Mirrors
# guacamole_url's custom-vs-cloudapp selection.
output "guacamole_fqdn" {
  value = local.guac_effective_fqdn
}

# ACME contact email surfaced to inventory.py for the same reason.
output "guacamole_acme_email" {
  value = var.services.guacamole.acme_email
}

output "guacamole_admin_user" {
  value = var.services.guacamole.admin_user
}

output "guacamole_admin_password" {
  description = "Operator's Guacamole admin password. When the scenario YAML left it blank (or set to a known-weak default like 'Lab!Guac1'), this is a per-deploy random 28-char password generated by random_password.guacamole_admin."
  value       = local.effective_guacamole_admin_password
  sensitive   = true
}

output "operator_ssh_private_key_path" {
  description = "Path to the auto-generated operator SSH private key. Use with `ssh -i <path> ranger@<vm-ip>`. Auto-generated unless the scenario YAML provides a real services.adaptix.ssh_pubkey."
  value       = local_sensitive_file.operator_private_key.filename
}

output "lab_dir" {
  description = "Per-deploy directory containing the SSH keypair and credentials.txt for this range. `./range destroy` removes this directory."
  value       = local.lab_dir
}

output "operator_ssh_public_key" {
  description = "Operator SSH public key embedded in every Linux VM's authorized_keys. Same key whether auto-generated or scenario-provided."
  value       = local.effective_ssh_pubkey
}

output "elk_kibana_url" {
  description = "Kibana URL — public when services.elk.public_ip = true (default), otherwise the internal address operators reach via Guacamole/Kali."
  value = (
    !var.services.elk.enabled ? "elk disabled" :
    var.services.elk.public_ip
    ? "http://${azurerm_public_ip.elk[0].ip_address}:5601"
    : "http://10.0.0.10:5601  (no public IP — open via Guacamole/Kali browser)"
  )
}

output "student_logins" {
  description = "Per-student Guacamole credentials."
  value = [
    for u in var.student_users : {
      student_id = u.student_id
      username   = u.username
      password   = u.password
    }
  ]
  sensitive = true
}

output "machine_ips" {
  description = "Machine name -> private IP, useful for debugging."
  value = {
    for m in var.machines :
    m.name => azurerm_network_interface.machine[m.name].private_ip_address
  }
}

output "summary" {
  value = {
    range          = var.range_name
    students       = var.students.count
    machines_total = length(var.machines)
    shared_total   = length(var.shared_machines)
    lockdown       = var.lockdown
    advanced_c2    = var.advanced_c2.enabled
  }
}

output "shared_infra" {
  description = "Per-tool address + SSH login for the shared red-team infra."
  value = {
    for s in var.shared_machines :
    s.name => {
      role       = s.role
      public_ip  = s.public_ip ? azurerm_public_ip.shared[s.name].ip_address : null
      private_ip = azurerm_network_interface.shared[s.name].private_ip_address
      ssh_user   = s.linux_user
      web_url = s.public_ip ? (
        s.role == "ghostwriter" ? "https://${azurerm_public_ip.shared[s.name].ip_address}/" :
        s.role == "stepping-stones" ? "http://${azurerm_public_ip.shared[s.name].ip_address}:8000/" :
        s.role == "redelk" ? "http://${azurerm_public_ip.shared[s.name].ip_address}:5601/" :
        "http://${azurerm_public_ip.shared[s.name].ip_address}/"
        ) : (
        # No public IP — operator reaches the web UI through Guacamole
        # (browser running on the Kali workstation, navigating to the
        # private IP).
        s.role == "ghostwriter" ? "https://${azurerm_network_interface.shared[s.name].private_ip_address}/  (via Guacamole/Kali)" :
        s.role == "stepping-stones" ? "http://${azurerm_network_interface.shared[s.name].private_ip_address}:8000/  (via Guacamole/Kali)" :
        s.role == "redelk" ? "http://${azurerm_network_interface.shared[s.name].private_ip_address}:5601/  (via Guacamole/Kali)" :
        "http://${azurerm_network_interface.shared[s.name].private_ip_address}/  (via Guacamole/Kali)"
      )
    }
  }
}

output "shared_infra_credentials" {
  description = "SSH + web-admin credentials for shared infra boxes."
  sensitive   = true
  value = {
    for s in var.shared_machines :
    s.name => {
      ssh_user     = s.linux_user
      ssh_password = s.linux_password
      # Web-admin login for the boxes that expose a web UI. For
      # stepping-stones the cloud-init userdata creates the Django
      # superuser as DJANGO_SUPERUSER_USERNAME=${linux_user},
      # DJANGO_SUPERUSER_PASSWORD=${linux_pass} (see
      # userdata/stepping-stones.sh) — i.e. the SAME credentials as SSH.
      # So we can surface them deterministically here; no need to read
      # /opt/stepping-stones/.admin-password off the box.
      #
      # ghostwriter + redelk web-admin passwords are set by their ANSIBLE
      # roles (ghostwriter_admin_password / redelk_es_password defaults
      # or vault overrides), NOT by terraform — so terraform can't surface
      # them here. They're reported by the role's own "Report" task at the
      # end of the repair/apply run. null here = "see role output".
      web_admin_user = (
        s.role == "stepping-stones" ? s.linux_user :
        s.role == "ghostwriter" ? "admin" :
        s.role == "redelk" ? "elastic" :
        null
      )
      web_admin_password = (
        s.role == "stepping-stones" ? s.linux_password :
        null # ghostwriter/redelk: ansible-managed, see role report
      )
      web_admin_note = (
        s.role == "ghostwriter" ? "password set by ansible (ghostwriter_admin_password); see ghostwriter role report" :
        s.role == "redelk" ? "password set by ansible (redelk_es_password); see redelk role report" :
        null
      )
    }
  }
}

output "adaptix_connections" {
  description = "Per-student AdaptixC2 teamserver coordinates for the operator client."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id     = m.student_id
      private_ip     = azurerm_network_interface.machine[m.name].private_ip_address
      commander_port = 9000
      operator_user  = m.linux_user
      password       = local.effective_adaptix_password[m.student_id]
    } if m.role == "c2-server"
  }
}

output "mythic_connections" {
  description = "Per-student Mythic teamserver coordinates (web UI + admin creds)."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id     = m.student_id
      private_ip     = azurerm_network_interface.machine[m.name].private_ip_address
      web_ui_port    = 7443 # Mythic upstream default; asymmetric vs Adaptix/BRC4 :9000
      admin_user     = "mythic_admin"
      admin_password = local.effective_mythic_password[m.student_id]
    } if m.role == "c2-mythic"
  }
}

output "brc4_connections" {
  description = "Per-student Brute Ratel C4 teamserver coordinates. The `automation_password` is a SECOND operator account on the BRC4 profile (user_list.automation) used by the brc4_payload Ansible role so its API session doesn't collide with the operator's Commander GUI session on the shared :9000 port."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id          = m.student_id
      private_ip          = azurerm_network_interface.machine[m.name].private_ip_address
      commander_port      = 9000
      admin_user          = "admin"
      admin_password      = local.effective_brc4_password[m.student_id]
      automation_user     = "automation"
      automation_password = local.effective_brc4_automation_password[m.student_id]
    } if m.role == "c2-brc4"
  }
}

output "sliver_connections" {
  description = "Per-student Sliver C2 teamserver coordinates. Operator config file lives at /opt/sliver-cfg/operator.cfg on the teamserver — SCP it down via Guacamole's Kali RDP session and `sliver-client import operator.cfg`."
  sensitive   = true
  value = {
    for m in var.machines :
    m.name => {
      student_id       = m.student_id
      private_ip       = azurerm_network_interface.machine[m.name].private_ip_address
      multiplayer_port = 31337
      operator_name    = "operator"
      operator_cfg     = "/opt/sliver-cfg/operator.cfg"
      seed_password    = local.effective_sliver_password[m.student_id]
    } if m.role == "c2-sliver"
  }
}

# Per-CDN (header_name, UUID, port) tables. Operators use these when
# configuring CloudFront / workers.dev / Fastly origin custom headers
# so requests reach the right teamserver listener through the redirector.
output "cdn_headers" {
  description = "Per-student-per-stack-per-CDN X-Api-* (name, value, port) tuples for origin header config."
  sensitive   = true
  value = {
    for sid in local.students :
    sid => {
      adaptix = local.cdn_headers["adaptix"][sid]
      mythic  = local.cdn_headers["mythic"][sid]
      brc4    = local.cdn_headers["brc4"][sid]
      sliver  = local.cdn_headers["sliver"][sid]
    }
  }
}

output "advanced_c2" {
  description = "Front Door endpoint and per-redirector domains. null when disabled."
  value = local.afd_enabled ? {
    profile_id   = azurerm_cdn_frontdoor_profile.main[0].resource_guid
    profile_name = azurerm_cdn_frontdoor_profile.main[0].name
    endpoint     = azurerm_cdn_frontdoor_endpoint.main[0].host_name
    routes = {
      for name, m in local.redirectors :
      name => {
        student_id = m.student_id
        fronts     = m.fronts
        subdomain  = local.redirector_subdomain[name]
        fqdn       = "${local.redirector_subdomain[name]}.${var.advanced_c2.domain}"
        public_ip  = azurerm_public_ip.redirector[name].ip_address
      }
    }
  } : null
}

# =============================================================================
# Ansible inventory feed.
# =============================================================================
# Single source of truth consumed by modules/azure/ansible/inventory.py.
# Designing the data shape HERE (not in inventory.py) keeps the layer
# above pure JSON-walking and lets terraform compute everything ansible
# needs (per-VM role, IP, jump-host, per-student creds, CDN headers).
#
# A note on jump hosts: Linux teamserver VMs (c2-server, c2-mythic,
# c2-brc4, c2-sliver) have NO public IP. Their paired redirector
# (<vm-name>-redir) DOES have a public IP. Ansible reaches the
# teamserver by SSHing to the redirector (operator NSG rule) and
# ProxyJumping to the teamserver's private IP (intra-subnet allowed).
# The inventory emits `ansible_ssh_common_args` with the ProxyJump
# string already filled in.
output "ansible_inventory" {
  description = "Structured inventory data for modules/azure/ansible/inventory.py — one entry per Linux VM with the SSH params (host, user, ProxyJump if needed) and per-student vars."
  sensitive   = true
  value = {
    ssh_private_key_path = local_sensitive_file.operator_private_key.filename
    # Map of student_id -> redirector public IP, keyed by which teamserver
    # the redirector pairs with (so a teamserver can find its redirector
    # by name lookup).
    # Keyed by FULL Azure VM name ("${var.range_name}-${m.name}") to
    # match the `hosts[].name` convention above. inventory.py builds the
    # jump-host lookup as `redirector_public_ips[f"{host.name}-redir"]`,
    # and host.name is the range-prefixed form (see vms.tf:331), so the
    # key here must match. The previous short-name keying ("adaptix-redir")
    # silently broke ProxyJump after we range-prefixed host names —
    # ansible's ssh command came out without `-o ProxyCommand`, then
    # tried to connect to the private IP directly and hit 186s timeouts.
    redirector_public_ips = {
      for name, m in local.redirectors :
      "${var.range_name}-${name}" => azurerm_public_ip.redirector[name].ip_address
    }
    # Extra operator-account credentials surfaced by the ansible roles
    # to create a second user (alongside the teamserver admin).
    # See `local.operator_ian` in passwords.tf.
    operator_ian = local.operator_ian
    # Custom Guacamole login-page wordmark (replaces "APACHE GUACAMOLE").
    # Threaded through to the guacamole role which bakes a translation
    # override into cwr-branding.jar.
    guacamole_login_title = (
      var.services.guacamole.enabled
      ? var.services.guacamole.login_title
      : "Guidem CWR"
    )
    # Guacamole public FQDN + ACME email used by the role's LE issuance
    # task. inventory.py surfaces these as `terra_guacamole_fqdn` /
    # `terra_guacamole_acme_email` group_vars on `all`. The role's
    # `Issue Let's Encrypt cert` task is gated on
    # `guac_acme_fqdn | length > 0`; missing here → task silently
    # skipped → cert stays self-signed even when the bootstrap script
    # is healthy. (Same fields are also top-level outputs, but the
    # ansible_inventory data dict is the single source inventory.py
    # consumes — we have to surface them here too.)
    guacamole_fqdn       = local.guac_effective_fqdn
    guacamole_acme_email = var.services.guacamole.acme_email
    # Base64 of the rendered manifest (same content cloud-init bakes into
    # /opt/guac/manifest.json at first boot). The Guac VM has
    # lifecycle.ignore_changes = [custom_data], so once that initial bake
    # happens the manifest never updates from terraform. The guacamole
    # ansible role writes THIS value to /opt/guac/manifest.json before
    # running register.py — that way subsequent edits to services.tf
    # (e.g. flipping a connection from RDP to VNC) actually land on the
    # live Guacamole DB after a `./range repair`. Without this, the
    # baked manifest wins forever and register.py keeps regressing
    # connections to whatever shape they had on day one.
    guacamole_manifest_b64 = base64encode(local.guac_manifest)
    # Per-VM ansible host entry. Includes:
    #   - host name (terraform VM name)
    #   - role (c2-server / c2-mythic / c2-brc4 / c2-sliver / c2-redirector)
    #   - student_id
    #   - private IP (the always-reachable address from the VNet's perspective)
    #   - public IP (null for teamservers; populated for redirectors)
    #   - ssh_user
    #   - linux_password (cleartext — needed for some non-key SSH setups,
    #     also stuffed into role vars for service auth)
    #   - role-specific creds + ports
    hosts = concat(
      # ---- Linux machines (c2 + redirector roles) ----
      # IMPORTANT: `name` must equal the actual Azure VM resource name
      # ("${var.range_name}-${m.name}" — see vms.tf:331). inventory.py's
      # state-walk fallback path keys off the VM resource name directly;
      # if this output emits the bare short name, switching paths would
      # change ansible hostnames (e.g. `mythic` vs `redteam-lab-mythic`)
      # and every playbook `hosts:` selector would silently mismatch.
      [
        for m in var.machines : {
          name       = "${var.range_name}-${m.name}"
          role       = m.role
          student_id = m.student_id
          private_ip = azurerm_network_interface.machine[m.name].private_ip_address
          public_ip  = try(azurerm_public_ip.redirector[m.name].ip_address, null)
          ssh_user   = m.linux_user
          # Per-VM linux user password (set by chpasswd in cloud-init).
          # Mostly informational — ansible uses key-based auth.
          linux_password = m.linux_password
          # The ACTUAL admin USERNAME on the Windows VM. Pulled from
          # the generator's per-machine win_admin_user field, which is
          # `rangeadmin` by default (or `var.domain.admin_user` for
          # windows-dc when domain.enabled). This is what
          # `azurerm_windows_virtual_machine.machine.admin_username`
          # is set to in vms.tf:516, so it MUST be what ansible
          # authenticates as. Without exposing this, inventory.py
          # would fall back to ssh_user="ranger" (the Linux convention)
          # and WinRM auth would fail with "credentials rejected"
          # because there's no `ranger` user on Windows.
          windows_admin_user = m.win_admin_user
          # The ACTUAL admin password for Windows VMs — populated by
          # random_password.domain_admin[student_id] at apply time and
          # planted as the local admin password in vms.tf's windows-*
          # branches. inventory.py uses this for ansible_password on
          # Windows hosts (winrm basic auth). Null on non-Windows
          # machines. Without this, ansible's WinRM auth would fail
          # with "the specified credentials were rejected by the
          # server" because the YAML's linux_password ("Lab!Linux1")
          # is just a placeholder for Windows — the real password is
          # the per-deploy random one terraform generates.
          windows_admin_password = try(local.effective_domain_password[m.student_id], null)
          # Per-role auth bundle. Ansible roles pick the fields they
          # need; missing fields are simply null on irrelevant VMs.
          adaptix_password = try(local.effective_adaptix_password[m.student_id], null)
          mythic_password  = try(local.effective_mythic_password[m.student_id], null)
          brc4_password    = try(local.effective_brc4_password[m.student_id], null)
          # BRC4 second operator ("automation") used by brc4_payload role
          # to drive the WebSocket API without kicking the Commander GUI.
          brc4_automation_password = try(local.effective_brc4_automation_password[m.student_id], null)
          sliver_password          = try(local.effective_sliver_password[m.student_id], null)
          cdn_headers = try(local.cdn_headers[
            m.role == "c2-server" ? "adaptix" :
            m.role == "c2-mythic" ? "mythic" :
            m.role == "c2-brc4" ? "brc4" :
            m.role == "c2-sliver" ? "sliver" : "adaptix"
          ][m.student_id], null)
          # Per-CDN beacon callback addresses for this teamserver. azure
          # resolves to the AFD-fronted redirector subdomain when
          # advanced_c2 is enabled, otherwise to the local redirector's
          # public IP. cloudfront / workers / fastly / other stay as
          # "CHANGEME-<cdn>-<sid>:443" placeholders by default until
          # the operator supplies real CDN hostnames.
          #
          # IMPORTANT: AdaptixServer's BeaconHTTP listener parses each
          # callback_addresses entry with `net.SplitHostPort` — feeding
          # a full URL (https://host:443/) yields "Invalid address
          # (cannot split host:port)". So we emit just `host:port`;
          # the listener applies ssl:true and uri:/endpoint separately.
          adaptix_callbacks = (m.role == "c2-server"
            ? {
              for cdn in local.cdn_names :
              cdn => (
                cdn == "azure"
                ? "${local.azure_callback_for["c2-server"][m.student_id]}:443"
                : "CHANGEME-${cdn}-${m.student_id}:443"
              )
            }
            : null
          )
          # Mythic-side equivalent. Mythic's http C2 profile params
          # take a full URL for `callback_host` (unlike Adaptix's bare
          # host:port). When AFD is on, the redirector's AFD-fronted
          # subdomain becomes the beacon callback. The Ansible role
          # reads this as `terra_mythic_callback_host` and pre-fills
          # the http profile's `default_value` in Postgres via the
          # Hasura admin secret, so Create Payload → http → fields are
          # populated on first open.
          mythic_callback_host = (m.role == "c2-mythic"
            ? "https://${local.azure_callback_for["c2-mythic"][m.student_id]}"
            : null
          )
          # BRC4-side equivalent. listeners.tf renders a per-student
          # c2.profile (5 HTTPS listeners on :8443-:8447 + commander).
          # The c2-brc4.sh userdata drops it at boot; the brc4 Ansible
          # role reads it back as `terra_brc4_profile` and keeps
          # /opt/bruteratel/{profiles/c2.profile,autosave.profile} in
          # sync with this render on every `./range repair`. Null on
          # non-c2-brc4 hosts.
          brc4_profile = (m.role == "c2-brc4"
            ? local.brc4_profile[m.student_id]
            : null
          )
          # Include every role ansible-playbook targets. Two groups:
          #
          # (a) Linux roles managed end-to-end by ansible: the C2 stack
          #     (server/mythic/brc4/sliver/redirector), kali (role=attacker
          #     → groups [linux,kali]) and the generic linux-target.
          #
          # (b) Windows roles. Boot-time bring-up is still
          #     `azurerm_virtual_machine_run_command.windows_*` (cheap WinRM
          #     wasn't reachable before NSG + listener exist), so the
          #     run-command layer enables WinRM and joins the domain. AFTER
          #     boot, the `windows-base` ansible role applies the machine-
          #     wide wallpaper policy + future Windows config via the WinRM
          #     connection plugin. inventory.py maps each windows-* role
          #     into the `windows` parent group (see WINDOWS_ROLES /
          #     role_to_groups), and inventory swaps the SSH connection
          #     vars for WinRM (port 5985, basic auth, http scheme).
          #
          # If you add a new Windows role (e.g. windows-fileshare), append
          # it to BOTH the contains() list below AND inventory.py's
          # role_to_groups + WINDOWS_ROLES sets — otherwise the host shows
          # up in inventory but ansible can't connect, or the play matches
          # zero hosts.
          } if contains([
            "c2-server", "c2-mythic", "c2-brc4", "c2-sliver", "c2-redirector",
            "attacker", "linux-target",
            "windows-dc", "windows-member", "windows-workstation",
            "windows-analyst", "windows-blank", "windows-persona",
        ], m.role)
      ],
      # ---- Guacamole (1 VM, no Role tag, identified by name suffix) ----
      # ssh user/password live on the VM resource itself
      # (see modules/azure/services.tf around `azurerm_linux_virtual_machine.guacamole`):
      #   admin_username = "guacadmin"
      #   admin_password = local.effective_guacamole_admin_password
      var.services.guacamole.enabled ? [{
        name                     = "${var.range_name}-guac"
        role                     = "guacamole"
        student_id               = "shared"
        private_ip               = azurerm_network_interface.guacamole[0].private_ip_address
        public_ip                = azurerm_public_ip.guacamole[0].ip_address
        ssh_user                 = "guacadmin"
        linux_password           = local.effective_guacamole_admin_password
        adaptix_password         = null
        mythic_password          = null
        brc4_password            = null
        brc4_automation_password = null
        sliver_password          = null
        cdn_headers              = null
      }] : [],
      # ---- Shared infra (RedELK / Ghostwriter / SteppingStones / ELK) ----
      # Only those with SSH access. Public_ip may be null when the operator
      # reaches the box via Guacamole/Kali instead.
      # Shared infra: same range-prefix convention so inventory hostnames
      # match the actual Azure VM names (see shared_infra.tf:67).
      [
        for s in var.shared_machines : {
          name                     = "${var.range_name}-${s.name}"
          role                     = s.role
          student_id               = "shared"
          private_ip               = azurerm_network_interface.shared[s.name].private_ip_address
          public_ip                = s.public_ip ? azurerm_public_ip.shared[s.name].ip_address : null
          ssh_user                 = s.linux_user
          linux_password           = s.linux_password
          adaptix_password         = null
          mythic_password          = null
          brc4_password            = null
          brc4_automation_password = null
          sliver_password          = null
          cdn_headers              = null
        }
      ],
    )
  }
}

# Per-student randomized credentials, operator-only. Students never see
# these — they have to compromise the lab to discover them. Per-CDN
# X-Api headers live in the dedicated `cdn_headers` output.
output "student_credentials" {
  description = "Per-student random Domain Admin / Adaptix / Mythic / BRC4 / Sliver passwords. Operator-only."
  sensitive   = true
  value = {
    for sid in local.students :
    sid => {
      domain_admin_user        = var.domain.admin_user
      domain_admin_password    = local.effective_domain_password[sid]
      adaptix_teamserver_pw    = local.effective_adaptix_password[sid]
      mythic_admin_user        = "mythic_admin"
      mythic_admin_password    = local.effective_mythic_password[sid]
      brc4_teamserver_password = local.effective_brc4_password[sid]
      brc4_automation_password = local.effective_brc4_automation_password[sid]
      sliver_seed_password     = local.effective_sliver_password[sid]
    }
  }
}
